const BAD_CHAT_LIST_GLOBAL = [
    "Is Coots going to do something interesting soon?",
    "I'm so bored, I might as well watch Coots sleep",
    "Can we get some new toys for Coots to play with?",
    "Watching Coots groom himself is getting old",
    "Is Coots ever going to interact with us?",
    "I can't believe I've been watching Coots for hours",
    "Coots is cute, but this stream is getting dull",
    "I wish there was more to do in this chat",
    "I'm starting to doze off watching Coots",
    "I'm going to switch to a different stream, this is too boring",
    "Is it just me or has Coots been napping all day?",
    "I need some excitement, this stream isn't cutting it",
    "Coots is great, but this stream needs more variety",
    "This stream is starting to feel like a snooze-fest",
    "I think I've seen Coots do the same thing over and over again",
    "I'm losing interest in this stream fast",
    "I'm starting to regret choosing this stream to watch",
    "Coots is cute and all, but this is getting tedious",
    "I need something more engaging than watching Coots sleep",
    "I might as well do something else while I watch this boring stream",
    "Is this all there is to the Coots stream?",
    "I wish there was more interaction with viewers",
    "I don't know how much longer I can keep watching this",
    "Coots is adorable, but this stream is putting me to sleep",
    "I thought this stream would be more entertaining",
    "Coots is cute, but can we get some new content?",
    "I'm so bored, I might as well be watching paint dry",
    "I'm getting tired of watching Coots do nothing",
    "Can we get some games or activities for Coots to do?",
    "I need something to keep my attention, and this isn't it",
    "I wish Coots would do something other than nap",
    "Is there a way to make this stream more interesting?",
    "I'm starting to feel like I'm wasting my time here",
    "I'm losing interest in this stream by the minute",
    "I need a change of pace, this is too boring",
    "Coots is adorable, but this stream needs more excitement",
    "I wish I could interact more with Coots and other viewers",
    "I'm not sure how much longer I can handle this monotony",
    "Coots is cute, but this stream needs more variety",
    "I'm starting to question why I'm even watching this",
    "I'm starting to feel like I'm wasting my time watching this",
    "Coots is cute, but this stream needs some action",
    "I'm getting tired of watching Coots do the same thing over and over",
    "I need something to liven up this stream",
    "Can we get some more excitement in here?",
    "I'm looking for a more engaging stream experience",
    "I'm getting restless watching Coots nap all day",
    "I wish there was something more to this stream",
    "I thought this would be more interesting than it is",
    "I'm struggling to stay awake watching this stream"
]